// Movion Constants - Mock Data

import { VideoType, MovionVideo, MovionChannel } from './types';

export const MONETIZATION_GOALS = {
  SUBSCRIBERS: 2500,
  WATCH_TIME_HOURS: 7500,
  SHORTS_VIEWS: 3000000
};

export const MOCK_CHANNELS: MovionChannel[] = [
  {
    id: 'c1',
    name: 'Tech Insider',
    handle: '@techinsider',
    avatar: 'https://picsum.photos/seed/tech/100/100',
    subscribers: 1250000,
    description: 'The latest in tech and innovation.',
    watchTimeHours: 45000,
    shortsViews: 12000000,
    joinedDate: 'Jan 2020'
  },
  {
    id: 'my-channel',
    name: 'Your Awesome Channel',
    handle: '@user123',
    avatar: 'https://picsum.photos/seed/user/100/100',
    subscribers: 1200, 
    description: 'Personal vlogs and gaming.',
    watchTimeHours: 4200,
    shortsViews: 1500000,
    joinedDate: 'Mar 2023'
  },
  {
    id: 'c3',
    name: 'Global Cooking',
    handle: '@globalcooking',
    avatar: 'https://picsum.photos/seed/chef/100/100',
    subscribers: 850000,
    description: 'Recipes from around the globe.',
    watchTimeHours: 32000,
    shortsViews: 8000000,
    joinedDate: 'Jun 2021'
  }
];

export const MOCK_VIDEOS: MovionVideo[] = [
  {
    id: 'v1',
    title: 'Future of Quantum Computing: Beyond the Hype',
    description: "Diving deep into how quantum computers will change the world.\n\n#Quantum #Tech #Science #Future",
    thumbnail: 'https://picsum.photos/seed/quantum/640/360',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    type: VideoType.LONG,
    views: 1200000,
    likes: 45000,
    dislikes: 1200,
    timestamp: '2 days ago',
    duration: '12:45',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Tech'
  },
  {
    id: 'v2',
    title: 'I Traveled to Find the Worlds Best Coffee',
    description: 'We traveled to Ethiopia to find the perfect bean.',
    thumbnail: 'https://picsum.photos/seed/coffee/640/360',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    type: VideoType.LONG,
    views: 850000,
    likes: 32000,
    dislikes: 450,
    timestamp: '5 hours ago',
    duration: '08:20',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Travel'
  },
  {
    id: 'v3',
    title: 'React 19: Everything You Need to Know',
    description: 'The biggest update to React in years is finally here.',
    thumbnail: 'https://picsum.photos/seed/react/640/360',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    type: VideoType.LONG,
    views: 250000,
    likes: 12000,
    dislikes: 80,
    timestamp: '1 week ago',
    duration: '15:30',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Programming'
  },
  {
    id: 'v4',
    title: 'Building a 100% Transparent PC',
    description: 'Is it actually possible? Let\'s find out.',
    thumbnail: 'https://picsum.photos/seed/pc/640/360',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    type: VideoType.LONG,
    views: 3400000,
    likes: 210000,
    dislikes: 5000,
    timestamp: '3 days ago',
    duration: '22:15',
    channelId: 'my-channel',
    channelName: 'Your Awesome Channel',
    channelAvatar: 'https://picsum.photos/seed/user/100/100',
    category: 'Computers'
  },
  {
    id: 'v5',
    title: 'Mastering the Art of Sushi',
    description: 'A professional chef shows how to make perfect nigiri.',
    thumbnail: 'https://picsum.photos/seed/sushi/640/360',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    type: VideoType.LONG,
    views: 780000,
    likes: 56000,
    dislikes: 230,
    timestamp: '12 hours ago',
    duration: '10:45',
    channelId: 'c3',
    channelName: 'Global Cooking',
    channelAvatar: 'https://picsum.photos/seed/chef/100/100',
    category: 'Cooking'
  },
  {
    id: 'v6',
    title: 'The Mars Mission: 2025 Update',
    description: 'NASA\'s latest plans for the red planet.',
    thumbnail: 'https://picsum.photos/seed/mars/640/360',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    type: VideoType.LONG,
    views: 1100000,
    likes: 89000,
    dislikes: 1500,
    timestamp: '4 days ago',
    duration: '18:50',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Science'
  },
  // SHORTS
  {
    id: 's1',
    title: 'Satisfying Kinetic Sand 🌈',
    description: 'ASMR kinetic sand slicing.',
    thumbnail: 'https://picsum.photos/seed/sand/360/640',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    type: VideoType.SHORT,
    views: 5000000,
    likes: 250000,
    dislikes: 12000,
    timestamp: '1 day ago',
    duration: '0:15',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'ASMR'
  },
  {
    id: 's2',
    title: 'Insane Basketball Trickshot!',
    description: 'Wait for the end...',
    thumbnail: 'https://picsum.photos/seed/hoops/360/640',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4',
    type: VideoType.SHORT,
    views: 2200000,
    likes: 180000,
    dislikes: 3000,
    timestamp: '4 hours ago',
    duration: '0:15',
    channelId: 'my-channel',
    channelName: 'Your Awesome Channel',
    channelAvatar: 'https://picsum.photos/seed/user/100/100',
    category: 'Comedy'
  },
  {
    id: 's3',
    title: 'Exploring Underwater Caves 🌊',
    description: 'Pure adrenaline!',
    thumbnail: 'https://picsum.photos/seed/ocean/360/640',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerFun.mp4',
    type: VideoType.SHORT,
    views: 1200000,
    likes: 95000,
    dislikes: 500,
    timestamp: '2 days ago',
    duration: '0:15',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Nature'
  },
  {
    id: 's4',
    title: 'New Smartphone Unboxing 📱',
    description: 'The cameras are wild.',
    thumbnail: 'https://picsum.photos/seed/phone/360/640',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4',
    type: VideoType.SHORT,
    views: 800000,
    likes: 42000,
    dislikes: 1200,
    timestamp: '1 hour ago',
    duration: '0:15',
    channelId: 'my-channel',
    channelName: 'Your Awesome Channel',
    channelAvatar: 'https://picsum.photos/seed/user/100/100',
    category: 'Tech'
  },
  {
    id: 's5',
    title: 'Morning Yoga Routine 🧘‍♀️',
    description: 'Start your day right.',
    thumbnail: 'https://picsum.photos/seed/yoga/360/640',
    videoUrl: 'https://storage.googleapis.com/gtv-videos-bucket/sample/ForBiggerMeltdowns.mp4',
    type: VideoType.SHORT,
    views: 450000,
    likes: 12000,
    dislikes: 150,
    timestamp: '3 days ago',
    duration: '0:15',
    channelId: 'c3',
    channelName: 'Global Cooking',
    channelAvatar: 'https://picsum.photos/seed/chef/100/100',
    category: 'Lifestyle'
  },
  {
    id: 'v7',
    title: '10 Programming Languages for 2025',
    description: 'What should you learn next year?',
    thumbnail: 'https://picsum.photos/seed/code/640/360',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    type: VideoType.LONG,
    views: 120000,
    likes: 9000,
    dislikes: 300,
    timestamp: '1 day ago',
    duration: '25:12',
    channelId: 'c1',
    channelName: 'Tech Insider',
    channelAvatar: 'https://picsum.photos/seed/tech/100/100',
    category: 'Programming'
  },
  {
    id: 'v8',
    title: 'Why I Switched to Linux',
    description: 'My experience after 30 days.',
    thumbnail: 'https://picsum.photos/seed/linux/640/360',
    videoUrl: 'https://www.w3schools.com/html/movie.mp4',
    type: VideoType.LONG,
    views: 450000,
    likes: 28000,
    dislikes: 2100,
    timestamp: '6 days ago',
    duration: '14:20',
    channelId: 'my-channel',
    channelName: 'Your Awesome Channel',
    channelAvatar: 'https://picsum.photos/seed/user/100/100',
    category: 'Computers'
  }
];

export const VIDEO_CATEGORIES = [
  'All', 'Tech', 'Gaming', 'Music', 'Cooking', 'Travel', 
  'Science', 'Programming', 'Lifestyle', 'Comedy', 'Nature', 'New to you'
];
