project_id = "plmhjuqedtkiffzhberf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.startup-voice]
    verify_jwt = false
