project_id = "plmhjuqedtkiffzhberf"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.create-conversation]
    verify_jwt = true
  [functions.seed-demo-data]
    verify_jwt = true
