/**
 * Shared group categories used in both the Create Group form and the Groups page filter bar.
 * Each entry has a label (with emoji) for display and a value for DB storage/filtering.
 */
export const GROUP_CATEGORIES = [
  { label: "🔥 Trending", value: "trending" },
  { label: "💻 Technology", value: "Technology" },
  { label: "🎮 Gaming", value: "Gaming" },
  { label: "🎵 Music", value: "Music" },
  { label: "⚽ Sports", value: "Sports" },
  { label: "🎬 Movies & TV", value: "Movies & TV" },
  { label: "📚 Books", value: "Books" },
  { label: "🍳 Cooking", value: "Cooking" },
  { label: "✈️ Travel", value: "Travel" },
  { label: "📸 Photography", value: "Photography" },
  { label: "🎨 Art & Design", value: "Art & Design" },
  { label: "👗 Fashion", value: "Fashion" },
  { label: "💄 Beauty", value: "Beauty" },
  { label: "💪 Fitness", value: "Fitness" },
  { label: "🧘 Mental Health", value: "Mental Health" },
  { label: "👶 Parenting", value: "Parenting" },
  { label: "🐾 Pets", value: "Pets" },
  { label: "🌿 Nature", value: "Nature" },
  { label: "🔬 Science", value: "Science" },
  { label: "🎓 Education", value: "Education" },
  { label: "🏛️ Politics", value: "Politics" },
  { label: "🕌 Religion", value: "Religion" },
  { label: "💼 Business", value: "Business" },
  { label: "📈 Finance", value: "Finance" },
  { label: "🏠 Real Estate", value: "Real Estate" },
  { label: "📣 Marketing", value: "Marketing" },
  { label: "👨‍💻 Programming", value: "Programming" },
  { label: "🤖 AI & ML", value: "AI & ML" },
  { label: "🔐 Cybersecurity", value: "Cybersecurity" },
  { label: "₿ Crypto", value: "Crypto" },
  { label: "🖼️ NFT", value: "NFT" },
  { label: "🎌 Anime", value: "Anime" },
  { label: "📖 Comics", value: "Comics" },
  { label: "🎤 K-Pop", value: "K-Pop" },
  { label: "🎧 Hip-Hop", value: "Hip-Hop" },
  { label: "🎸 Rock Music", value: "Rock Music" },
  { label: "🎻 Classical Music", value: "Classical Music" },
  { label: "🎷 Jazz", value: "Jazz" },
  { label: "🎙️ Podcasts", value: "Podcasts" },
  { label: "▶️ YouTube", value: "YouTube" },
  { label: "📡 Streaming", value: "Streaming" },
  { label: "🎥 Videography", value: "Videography" },
  { label: "🖌️ Graphic Design", value: "Graphic Design" },
  { label: "📐 UI/UX", value: "UI/UX" },
  { label: "🏗️ Architecture", value: "Architecture" },
  { label: "🛋️ Interior Design", value: "Interior Design" },
  { label: "🔨 DIY & Crafts", value: "DIY & Crafts" },
  { label: "🧁 Baking", value: "Baking" },
  { label: "🥗 Veganism", value: "Veganism" },
  { label: "🏃 Running", value: "Running" },
  { label: "🚴 Cycling", value: "Cycling" },
  { label: "🏋️ Gym", value: "Gym" },
  { label: "⚽ Football", value: "Football" },
  { label: "🏀 Basketball", value: "Basketball" },
  { label: "🏏 Cricket", value: "Cricket" },
  { label: "🎾 Tennis", value: "Tennis" },
  { label: "⚾ Baseball", value: "Baseball" },
  { label: "🏊 Swimming", value: "Swimming" },
  { label: "🥋 Martial Arts", value: "Martial Arts" },
  { label: "♟️ Chess", value: "Chess" },
  { label: "🎲 Board Games", value: "Board Games" },
  { label: "🕹️ Video Games", value: "Video Games" },
  { label: "🖥️ PC Gaming", value: "PC Gaming" },
  { label: "📱 Mobile Gaming", value: "Mobile Gaming" },
  { label: "👾 Retro Gaming", value: "Retro Gaming" },
  { label: "🏆 Esports", value: "Esports" },
  { label: "🎭 Cosplay", value: "Cosplay" },
  { label: "🥾 Hiking", value: "Hiking" },
  { label: "⛺ Camping", value: "Camping" },
  { label: "🏄 Adventure Sports", value: "Adventure Sports" },
  { label: "🎣 Fishing", value: "Fishing" },
  { label: "🌱 Gardening", value: "Gardening" },
  { label: "🚗 Cars", value: "Cars" },
  { label: "🏍️ Motorcycles", value: "Motorcycles" },
  { label: "✈️ Aviation", value: "Aviation" },
  { label: "🚀 Space", value: "Space" },
  { label: "📜 History", value: "History" },
  { label: "💬 Philosophy", value: "Philosophy" },
  { label: "🗣️ Languages", value: "Languages" },
  { label: "💕 Relationships", value: "Relationships" },
  { label: "🏳️‍🌈 LGBTQ+", value: "LGBTQ+" },
  { label: "👩 Women Empowerment", value: "Women Empowerment" },
  { label: "😂 Humor & Memes", value: "Humor & Memes" },
  { label: "❓ Trivia", value: "Trivia" },
  { label: "📰 News", value: "News" },
  { label: "🏘️ Local Community", value: "Local Community" },
  { label: "📝 Study Groups", value: "Study Groups" },
  { label: "💼 Career & Jobs", value: "Career & Jobs" },
  { label: "🧑‍🎨 Freelancing", value: "Freelancing" },
  { label: "🚀 Startups", value: "Startups" },
  { label: "🛍️ E-commerce", value: "E-commerce" },
  { label: "✂️ Photo Editing", value: "Photo Editing" },
  { label: "🎬 Video Editing", value: "Video Editing" },
  { label: "🎹 Music Production", value: "Music Production" },
  { label: "✍️ Writing", value: "Writing" },
  { label: "📜 Poetry", value: "Poetry" },
  { label: "🎤 Stand-Up Comedy", value: "Stand-Up Comedy" },
  { label: "🎭 Theater", value: "Theater" },
  { label: "💃 Dance", value: "Dance" },
  { label: "🥊 Boxing", value: "Boxing" },
  { label: "🤼 Wrestling", value: "Wrestling" },
  { label: "🛹 Skateboarding", value: "Skateboarding" },
  { label: "🏄 Surfing", value: "Surfing" },
  { label: "🏂 Snowboarding", value: "Snowboarding" },
  { label: "⛳ Golf", value: "Golf" },
  { label: "🏇 Horse Riding", value: "Horse Riding" },
  { label: "🏐 Volleyball", value: "Volleyball" },
  { label: "🏸 Badminton", value: "Badminton" },
  { label: "🏓 Table Tennis", value: "Table Tennis" },
  { label: "🏹 Archery", value: "Archery" },
  { label: "🧗 Climbing", value: "Climbing" },
  { label: "🥷 Parkour", value: "Parkour" },
  { label: "🥽 Virtual Reality", value: "Virtual Reality" },
  { label: "🖨️ 3D Printing", value: "3D Printing" },
  { label: "🤖 Robotics", value: "Robotics" },
  { label: "⚡ Electronics", value: "Electronics" },
  { label: "🏠 Home Automation", value: "Home Automation" },
  { label: "🪵 Woodworking", value: "Woodworking" },
  { label: "⚙️ Metalworking", value: "Metalworking" },
  { label: "🖼️ Digital Art", value: "Digital Art" },
  { label: "🎨 Watercolor", value: "Watercolor" },
  { label: "🖌️ Oil Painting", value: "Oil Painting" },
  { label: "✏️ Sketching", value: "Sketching" },
  { label: "🌌 Street Art", value: "Street Art" },
  { label: "🪡 Tattoo Art", value: "Tattoo Art" },
  { label: "⭐ Astrology", value: "Astrology" },
  { label: "🔮 Tarot", value: "Tarot" },
  { label: "🧘 Wellness", value: "Wellness" },
  { label: "🧠 Psychology", value: "Psychology" },
  { label: "🥦 Nutrition", value: "Nutrition" },
  { label: "👨‍👩‍👧 Family", value: "Family" },
  { label: "🏫 College Life", value: "College Life" },
  { label: "🌍 Environment", value: "Environment" },
  { label: "🌊 Ocean & Marine", value: "Ocean & Marine" },
  { label: "🏕️ Outdoor Life", value: "Outdoor Life" },
  { label: "🎪 Events", value: "Events" },
  { label: "🛠️ Tools & Hardware", value: "Tools & Hardware" },
  { label: "🧪 Chemistry", value: "Chemistry" },
  { label: "🧬 Biology", value: "Biology" },
  { label: "🔭 Astronomy", value: "Astronomy" },
  { label: "🗺️ Geography", value: "Geography" },
  { label: "📊 Data Science", value: "Data Science" },
  { label: "☁️ Cloud Computing", value: "Cloud Computing" },
  { label: "📲 App Development", value: "App Development" },
  { label: "🌐 Web Development", value: "Web Development" },
  { label: "🎯 Self Improvement", value: "Self Improvement" },
  { label: "🕊️ Spirituality", value: "Spirituality" },
  { label: "🧩 Puzzles", value: "Puzzles" },
  { label: "🎠 Hobbies", value: "Hobbies" },
  { label: "🎁 Shopping", value: "Shopping" },
  { label: "🍕 Food & Drinks", value: "Food & Drinks" },
  { label: "🏥 Healthcare", value: "Healthcare" },
  { label: "⚖️ Law & Legal", value: "Law & Legal" },
  { label: "🎓 University", value: "University" },
  { label: "🏦 Banking", value: "Banking" },
  { label: "📱 Social Media", value: "Social Media" },
  { label: "🎪 Festivals", value: "Festivals" },
  { label: "🧵 Sewing & Knitting", value: "Sewing & Knitting" },
  { label: "🎀 Crafting", value: "Crafting" },
  { label: "🏎️ Formula 1", value: "Formula 1" },
  { label: "🚁 Drones", value: "Drones" },
  { label: "📻 Radio & Ham", value: "Radio & Ham" },
  { label: "🎯 Archery & Shooting", value: "Archery & Shooting" },
  { label: "🧳 Backpacking", value: "Backpacking" },
  { label: "🏖️ Beach Life", value: "Beach Life" },
  { label: "⛷️ Skiing", value: "Skiing" },
  { label: "🎿 Winter Sports", value: "Winter Sports" },
  { label: "🏄‍♀️ Water Sports", value: "Water Sports" },
  { label: "🎯 Darts", value: "Darts" },
  { label: "🎳 Bowling", value: "Bowling" },
  { label: "🏑 Hockey", value: "Hockey" },
  { label: "🏉 Rugby", value: "Rugby" },
  { label: "🤸 Gymnastics", value: "Gymnastics" },
  { label: "⛸️ Ice Skating", value: "Ice Skating" },
  { label: "🧘‍♂️ Yoga", value: "Yoga" },
  { label: "🥘 World Cuisine", value: "World Cuisine" },
  { label: "☕ Coffee & Tea", value: "Coffee & Tea" },
  { label: "🍷 Wine & Spirits", value: "Wine & Spirits" },
  { label: "🍺 Craft Beer", value: "Craft Beer" },
  { label: "📖 Literature", value: "Literature" },
  { label: "🎪 Circus Arts", value: "Circus Arts" },
  { label: "🎨 Calligraphy", value: "Calligraphy" },
  { label: "📷 Film Photography", value: "Film Photography" },
  { label: "🎞️ Filmmaking", value: "Filmmaking" },
  { label: "📺 TV Shows", value: "TV Shows" },
  { label: "🎬 Bollywood", value: "Bollywood" },
  { label: "🎬 Hollywood", value: "Hollywood" },
  { label: "🎬 K-Drama", value: "K-Drama" },
  { label: "🐕 Dogs", value: "Dogs" },
  { label: "🐈 Cats", value: "Cats" },
  { label: "🐦 Birds", value: "Birds" },
  { label: "🐠 Aquarium & Fish", value: "Aquarium & Fish" },
  { label: "🐴 Horses", value: "Horses" },
  { label: "🦎 Reptiles", value: "Reptiles" },
  { label: "💎 Jewelry Making", value: "Jewelry Making" },
  { label: "🏺 Pottery & Ceramics", value: "Pottery & Ceramics" },
  { label: "📐 Mathematics", value: "Mathematics" },
  { label: "⚛️ Physics", value: "Physics" },
  { label: "🧮 Engineering", value: "Engineering" },
  { label: "🏗️ Civil Engineering", value: "Civil Engineering" },
  { label: "⚡ Electrical Engineering", value: "Electrical Engineering" },
  { label: "🔧 Mechanical Engineering", value: "Mechanical Engineering" },
  { label: "💊 Pharmacy", value: "Pharmacy" },
  { label: "🩺 Medicine", value: "Medicine" },
  { label: "🦷 Dentistry", value: "Dentistry" },
  { label: "👁️ Optometry", value: "Optometry" },
  { label: "🧪 Research", value: "Research" },
  { label: "🎖️ Military & Defense", value: "Military & Defense" },
  { label: "🚒 Emergency Services", value: "Emergency Services" },
  { label: "🌾 Agriculture", value: "Agriculture" },
  { label: "🏭 Manufacturing", value: "Manufacturing" },
  { label: "🚢 Shipping & Logistics", value: "Shipping & Logistics" },
  { label: "🛩️ Aerospace", value: "Aerospace" },
  { label: "🔋 Renewable Energy", value: "Renewable Energy" },
  { label: "♻️ Sustainability", value: "Sustainability" },
  { label: "🌐 Globalization", value: "Globalization" },
  { label: "📦 Supply Chain", value: "Supply Chain" },
  { label: "🧑‍🍳 Culinary Arts", value: "Culinary Arts" },
  { label: "🎓 Scholarships", value: "Scholarships" },
  { label: "📝 Exam Preparation", value: "Exam Preparation" },
  { label: "🏆 Competitive Exams", value: "Competitive Exams" },
  { label: "💰 Investing", value: "Investing" },
  { label: "📉 Stock Market", value: "Stock Market" },
  { label: "🏡 Home Improvement", value: "Home Improvement" },
  { label: "🧹 Organization & Minimalism", value: "Organization & Minimalism" },
  { label: "🎶 Singing", value: "Singing" },
  { label: "🥁 Drumming", value: "Drumming" },
  { label: "🎺 Brass & Wind", value: "Brass & Wind" },
  { label: "🎼 Songwriting", value: "Songwriting" },
  { label: "📻 Electronic Music", value: "Electronic Music" },
  { label: "🧑‍💻 Open Source", value: "Open Source" },
  { label: "🐧 Linux", value: "Linux" },
  { label: "🎮 Game Design", value: "Game Design" },
  { label: "📱 iOS Development", value: "iOS Development" },
  { label: "🤖 Android Development", value: "Android Development" },
  { label: "🗄️ Databases", value: "Databases" },
  { label: "🔗 Blockchain Dev", value: "Blockchain Dev" },
  { label: "📡 IoT", value: "IoT" },
  { label: "🧮 DevOps", value: "DevOps" },
  { label: "🛡️ Privacy & Security", value: "Privacy & Security" },
  { label: "📊 Analytics", value: "Analytics" },
  { label: "🤝 Networking & Events", value: "Networking & Events" },
  { label: "🎗️ Charity & Volunteering", value: "Charity & Volunteering" },
  { label: "🌎 Cultural Exchange", value: "Cultural Exchange" },
  { label: "🧳 Expat Life", value: "Expat Life" },
  { label: "🏠 Remote Work", value: "Remote Work" },
  { label: "📋 Productivity", value: "Productivity" },
  { label: "📚 Book Club", value: "Book Club" },
  { label: "🎬 Movie Club", value: "Movie Club" },
  { label: "🗳️ Debate", value: "Debate" },
  { label: "🧩 General", value: "General" },
] as const;

/** Category values only (excluding "trending" which is a special filter) */
export const GROUP_CATEGORY_VALUES = GROUP_CATEGORIES
  .filter(c => c.value !== "trending")
  .map(c => c.value);

export type GroupCategory = typeof GROUP_CATEGORY_VALUES[number];
