import { useEffect, useRef, useState } from "react";
import logo from "@/assets/sha-verse-logo.jpeg";

/**
 * StartupSplash
 * Premium 5s cinematic brand intro overlay. Renders above the app while it
 * hydrates, then fades out and unmounts. Does not block loading — the app
 * mounts and initialises behind the overlay in parallel.
 *
 * Adds:
 *  - Professional female narration ("SHA-VERSE: The Next Generation.")
 *    generated by Lovable AI TTS (cached via browser Cache Storage).
 *  - Cinematic ambient background music generated in-browser with WebAudio
 *    (copyright-safe, no vocals, no external files).
 *  - Automatic ducking of music while narration is speaking.
 *  - Respect for muted devices, prefers-reduced-motion, and autoplay blocks.
 *
 * Shows once per browser session (sessionStorage).
 */
const SESSION_KEY = "__sv_splash_shown__";
const TOTAL_MS = 5000;
const FADE_OUT_MS = 420;

const VOICE_ENDPOINT = `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/startup-voice`;
const VOICE_CACHE_KEY = "sv-startup-voice-v1";

/** Fetch narration MP3, cached in the browser's Cache Storage. */
const loadVoiceBlob = async (signal: AbortSignal): Promise<Blob | null> => {
  try {
    if ("caches" in window) {
      const cache = await caches.open(VOICE_CACHE_KEY);
      const cached = await cache.match(VOICE_ENDPOINT);
      if (cached) return await cached.blob();
      const res = await fetch(VOICE_ENDPOINT, { signal });
      if (!res.ok) return null;
      try {
        await cache.put(VOICE_ENDPOINT, res.clone());
      } catch {
        /* opaque or storage full — ignore */
      }
      return await res.blob();
    }
    const res = await fetch(VOICE_ENDPOINT, { signal });
    return res.ok ? await res.blob() : null;
  } catch {
    return null;
  }
};

/**
 * Build a soft cinematic ambient pad using WebAudio oscillators + gentle filter.
 * No samples, no external assets. Returns a stop() that fades out cleanly.
 */
const startAmbientMusic = (
  ctx: AudioContext,
  masterGain: GainNode,
  now: number,
): (() => void) => {
  // Bus for the music, feeding into the ducking master gain.
  const musicBus = ctx.createGain();
  musicBus.gain.value = 0.0001;
  musicBus.connect(masterGain);

  // Warm low-pass to keep it soft under the voice.
  const lp = ctx.createBiquadFilter();
  lp.type = "lowpass";
  lp.frequency.value = 2200;
  lp.Q.value = 0.4;
  lp.connect(musicBus);

  // Subtle stereo shimmer via detuned pair — cinematic tech feel.
  // Frequencies form an inspirational suspended chord (C, G, D, A) an octave up.
  const freqs = [261.63, 392.0, 587.33, 880.0];
  const oscillators: OscillatorNode[] = [];
  const gains: GainNode[] = [];

  freqs.forEach((f, i) => {
    const osc = ctx.createOscillator();
    osc.type = i % 2 === 0 ? "sine" : "triangle";
    osc.frequency.value = f;
    osc.detune.value = (i - 1.5) * 4;

    const g = ctx.createGain();
    // Voice-friendly relative levels; higher notes softer.
    const base = i === 0 ? 0.18 : i === 1 ? 0.14 : i === 2 ? 0.10 : 0.07;
    g.gain.value = base;

    osc.connect(g).connect(lp);
    osc.start(now);
    oscillators.push(osc);
    gains.push(g);
  });

  // Slow LFO on filter cutoff for gentle motion.
  const lfo = ctx.createOscillator();
  const lfoGain = ctx.createGain();
  lfo.frequency.value = 0.25;
  lfoGain.gain.value = 350;
  lfo.connect(lfoGain).connect(lp.frequency);
  lfo.start(now);

  // Music fade-in 0.0 → 1.0s to ~0.38 (perceived 35–40%).
  musicBus.gain.setValueAtTime(0.0001, now);
  musicBus.gain.exponentialRampToValueAtTime(0.38, now + 1.0);

  const stop = () => {
    const t = ctx.currentTime;
    // Fade-out 1s smoothly then stop.
    try {
      musicBus.gain.cancelScheduledValues(t);
      musicBus.gain.setValueAtTime(Math.max(musicBus.gain.value, 0.0001), t);
      musicBus.gain.exponentialRampToValueAtTime(0.0001, t + 1.0);
    } catch {
      /* ignore */
    }
    const stopAt = t + 1.05;
    oscillators.forEach((o) => {
      try {
        o.stop(stopAt);
      } catch {
        /* ignore */
      }
    });
    try {
      lfo.stop(stopAt);
    } catch {
      /* ignore */
    }
  };
  return stop;
};

export const StartupSplash = () => {
  const [visible, setVisible] = useState(() => {
    if (typeof window === "undefined") return false;
    try {
      return !sessionStorage.getItem(SESSION_KEY);
    } catch {
      return true;
    }
  });
  const [leaving, setLeaving] = useState(false);

  useEffect(() => {
    if (!visible) return;
    try {
      sessionStorage.setItem(SESSION_KEY, "1");
    } catch {
      /* ignore */
    }

    const reduce =
      window.matchMedia?.("(prefers-reduced-motion: reduce)").matches ?? false;

    const timeouts: number[] = [];
    const abort = new AbortController();
    let ctx: AudioContext | null = null;
    let stopMusic: (() => void) | null = null;
    let voiceEl: HTMLAudioElement | null = null;
    let cancelled = false;

    // Kick off audio in parallel to the visual timeline. Any failure is silent.
    const startAudio = async () => {
      const AC: typeof AudioContext | undefined =
        (window as unknown as { AudioContext?: typeof AudioContext; webkitAudioContext?: typeof AudioContext })
          .AudioContext ||
        (window as unknown as { webkitAudioContext?: typeof AudioContext })
          .webkitAudioContext;
      if (!AC) return;
      try {
        ctx = new AC();
        if (ctx.state === "suspended") await ctx.resume().catch(() => {});
        // Muted-device / blocked autoplay heuristic.
        if (ctx.state !== "running") return;
      } catch {
        return;
      }

      // Master gain used for ducking. Voice plays through <audio> (its own gain
      // controlled by element.volume); music routes through this gain and is
      // attenuated while narration is playing.
      const master = ctx.createGain();
      master.gain.value = 1.0;
      master.connect(ctx.destination);

      const now = ctx.currentTime + 0.05;
      try {
        stopMusic = startAmbientMusic(ctx, master, now);
      } catch {
        stopMusic = null;
      }

      // Fetch voice in parallel; play at ~0.8s of the splash timeline.
      const blob = await loadVoiceBlob(abort.signal);
      if (cancelled || !blob) return;

      const url = URL.createObjectURL(blob);
      voiceEl = new Audio(url);
      voiceEl.preload = "auto";
      voiceEl.volume = 0.8;
      voiceEl.crossOrigin = "anonymous";

      const cleanupUrl = () => URL.revokeObjectURL(url);
      voiceEl.addEventListener("ended", () => {
        // Un-duck music smoothly.
        try {
          const t = ctx!.currentTime;
          master.gain.cancelScheduledValues(t);
          master.gain.setValueAtTime(master.gain.value, t);
          master.gain.linearRampToValueAtTime(1.0, t + 0.35);
        } catch {
          /* ignore */
        }
        cleanupUrl();
      });
      voiceEl.addEventListener("error", cleanupUrl);

      // Schedule narration start at 800ms into the splash.
      const startVoiceAt = window.setTimeout(async () => {
        if (cancelled || !voiceEl || !ctx) return;
        // Duck music while voice speaks.
        try {
          const t = ctx.currentTime;
          master.gain.cancelScheduledValues(t);
          master.gain.setValueAtTime(master.gain.value, t);
          master.gain.linearRampToValueAtTime(0.35, t + 0.15);
        } catch {
          /* ignore */
        }
        try {
          await voiceEl.play();
        } catch {
          /* autoplay blocked — silent */
        }
      }, 800);
      timeouts.push(startVoiceAt);
    };

    void startAudio();

    const fadeAt = reduce ? 500 : TOTAL_MS - FADE_OUT_MS;
    const unmountAt = reduce ? 500 + FADE_OUT_MS : TOTAL_MS;

    timeouts.push(window.setTimeout(() => setLeaving(true), fadeAt));
    timeouts.push(window.setTimeout(() => setVisible(false), unmountAt));

    return () => {
      cancelled = true;
      abort.abort();
      timeouts.forEach(clearTimeout);
      if (voiceEl) {
        try {
          voiceEl.pause();
        } catch {
          /* ignore */
        }
        voiceEl.src = "";
      }
      if (stopMusic) stopMusic();
      if (ctx) {
        const c = ctx;
        window.setTimeout(() => {
          c.close().catch(() => {});
        }, 1200);
      }
    };
  }, [visible]);

  if (!visible) return null;

  return (
    <div
      aria-hidden="true"
      style={{
        position: "fixed",
        inset: 0,
        zIndex: 2147483000,
        background: "#0b0f1a",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        overflow: "hidden",
        opacity: leaving ? 0 : 1,
        transition: `opacity ${FADE_OUT_MS}ms cubic-bezier(0.22,1,0.36,1)`,
        pointerEvents: leaving ? "none" : "auto",
        paddingTop: "env(safe-area-inset-top)",
        paddingBottom: "env(safe-area-inset-bottom)",
      }}
    >
      <style>{`
        @keyframes sv-logo-in {
          0%   { opacity: 0; transform: scale(0.9); }
          100% { opacity: 1; transform: scale(1); }
        }
        @keyframes sv-breathe {
          0%,100% { transform: scale(1); }
          50%     { transform: scale(1.035); }
        }
        @keyframes sv-glow-in {
          0%   { opacity: 0; }
          100% { opacity: 1; }
        }
        @keyframes sv-glow-out {
          0%   { opacity: 1; }
          100% { opacity: 0; }
        }
        .sv-splash-logo {
          width: min(38vw, 148px);
          height: min(38vw, 148px);
          border-radius: 28%;
          object-fit: cover;
          opacity: 0;
          transform: scale(0.9);
          animation:
            sv-logo-in 600ms cubic-bezier(0.22,1,0.36,1) 200ms forwards,
            sv-breathe 4200ms ease-in-out 1500ms 1;
          box-shadow: 0 10px 40px -10px rgba(0,0,0,0.6);
          will-change: transform, opacity;
        }
        .sv-splash-glow {
          position: absolute;
          width: min(90vw, 480px);
          height: min(90vw, 480px);
          border-radius: 50%;
          background: radial-gradient(
            circle,
            rgba(96,165,250,0.35) 0%,
            rgba(96,165,250,0.12) 35%,
            rgba(96,165,250,0) 70%
          );
          opacity: 0;
          filter: blur(8px);
          animation:
            sv-glow-in 900ms ease-out 900ms forwards,
            sv-glow-out 700ms ease-in 4100ms forwards;
          will-change: opacity;
        }
        @media (prefers-reduced-motion: reduce) {
          .sv-splash-logo, .sv-splash-glow {
            animation: none !important;
            opacity: 1 !important;
            transform: none !important;
          }
        }
      `}</style>
      <div className="sv-splash-glow" />
      <img src={logo} alt="" className="sv-splash-logo" draggable={false} />
    </div>
  );
};

export default StartupSplash;
