-- Delist all SECURITY DEFINER trigger functions from the API (they run automatically)
REVOKE EXECUTE ON FUNCTION public.sync_video_comments_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_book_comments_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_friend_request() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_group_members_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_channel_subscribers_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.lock_message_identity() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_group_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_group_join() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_group_join_request_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_blocked_user_join() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_blocked_user_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_book_rating_avg() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.silent_block_message() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_notification_to_blocked() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.remove_friendship_on_block() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.increment_app_promotion_views() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_comment_likes_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_poll_vote_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_monetization_financials() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_group_join() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_comment() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_video_views_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_friendship() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_payout_request_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_book() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_block() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_channel_monetization_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_channel_admin_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_video_likes_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_friendship_status() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_message() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_engagement_score() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.guard_message_recipient_update() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_group_post_admin_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_chat_media_extension() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_new_video() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_video() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_group_post_delete() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.stamp_message_status_times() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_like() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_novachat_settings_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.update_group_posts_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_novachat_pro_self_grant() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.prevent_monetization_self_grant() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_novachat_pro_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_novachat_pro_fields_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_promotion_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_friend_request() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_comment() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.activity_log_group_post() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.protect_reward_fields() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_story_views_count() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.enforce_group_post_approval() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_on_post_reaction() FROM PUBLIC, anon, authenticated;

-- Sensitive RPCs: signed-in users only (remove the implicit PUBLIC/anon grant)
REVOKE EXECUTE ON FUNCTION public.admin_approve_channel(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_approve_channel(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.admin_reject_channel(uuid, text) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.admin_reject_channel(uuid, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.check_book_duplicate(text, text, text) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.check_book_duplicate(text, text, text) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_book_file_hash(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.get_book_file_hash(uuid) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_profile_private_fields(uuid) FROM PUBLIC, anon;
GRANT  EXECUTE ON FUNCTION public.get_profile_private_fields(uuid) TO authenticated;

-- Internal-only rate-limit helper: server-side only
REVOKE EXECUTE ON FUNCTION public.check_rate_limit(text, text) FROM PUBLIC, anon, authenticated;
GRANT  EXECUTE ON FUNCTION public.check_rate_limit(text, text) TO service_role;