// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plmhjuqedtkiffzhberf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsbWhqdXFlZHRraWZmemhiZXJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ0MTIxNTYsImV4cCI6MjA3OTk4ODE1Nn0.q2lAnpxhy6QbPOKYjL8XrF5UBVBs9Pmlvx6rlN7TSNM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});